package core;

/**
 * Represents the possible actions a GameObject can take.
 */
public enum Option {

    STATUS, OLD_STATUS, SPACE, SIZE, SIGHT, LEVEL, CONTRACT, HEAT, ANIMATION,

    HEALTH, MAX_HEALTH, ENERGY, MAX_ENERGY, HEAL,

    WORK, SOURCE, RESOURCE, HUNT, DRINK, LOG, MASON, WELD, MINE,

    ENABLED, EVOLUTION, UPGRADE, TOTAL_CYCLE, CYCLE, ATTACK, DEFENCE,

    DEGRADATION_CYCLE, DEGRADATION_AMOUNT, DEGRADE,

    DESTROY, CONSTRUCT, CONSTRUCT_X, CONSTRUCT_Y
}
