package core;

public enum Options {

    LOCATION_KEY, VIEW_KEY, X_KEY, Y_KEY, HEALTH_KEY, STATUS_KEY, SPACE_KEY, SIZE_KEY, ENERGY_KEY,
    DEGRADATION_CYCLE_KEY, DEGRADATION_AMOUNT_KEY, SIGHT_KEY

}
