package core;

public enum Options {

    LOCATION_KEY, VIEW_KEY, X_KEY, Y_KEY, STATUS_KEY, SPACE_KEY, SIZE_KEY, SIGHT_KEY, CYCLE_KEY,

    HEALTH_KEY, MAX_HEALTH_KEY, DEGRADATION_CYCLE_KEY, DEGRADATION_AMOUNT_KEY, DEGRADE_KEY,
    ENERGY_KEY, MAX_ENERGY_KEY,

    CONTRACT_KEY, LEVEL_KEY,

    ENABLED_KEY, DESTROY_KEY, WORK_KEY, SOURCE_KEY,

    CONSTRUCT_KEY, CONSTRUCT_X_KEY, CONSTRUCT_Y_KEY
}
