package core;

public enum Option {

    STATUS, OLD_STATUS, SPACE, SIZE, SIGHT, LEVEL, CONTRACT,

    HEALTH, MAX_HEALTH, ENERGY, MAX_ENERGY, HEAL, SPEED,

    HUNT, DRINK, LOG, MASON, WELD, MINE,

    ENABLED, DESTROY, WORK, SOURCE, TOTAL_CYCLE, CYCLE, ATTACK, DEFENCE,

    DEGRADATION_CYCLE, DEGRADATION_AMOUNT, DEGRADE,

    CONSTRUCT, CONSTRUCT_X, CONSTRUCT_Y
}
